site_name: Fine-Tuning a small LLM (4Stats)
site_url: https://mahalanobis.github.io/Mahalanobis.io/ 

theme:
  name: cosmo
  features:
    - navigation.tabs
    - navigation.sections
    - search.highlight
    - content.code.copy
  palette:
    primary: 'blue grey'
    accent:  'light blue'

markdown_extensions:
  - pymdownx.arithmatex:
      generic: true

extra_javascript:
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax @3/es5/tex-mml-chtml.js

nav:
  - Intro: index.md
  - DoE: doe.md 

plugins:
  - search

